config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }, path: 'account', path_names: { sign_in: 'signin', sign_out: 'signout', password: 'password', sign_up: 'signup', edit: 'password/change' }

  authenticated :user do
    root 'student/dashboards#show', as: :authenticated_root
  end

  root 'pages#home'

  # STRIPE
  mount StripeEvent::Engine, at: '/stripe/webhook'

  # SHRINE
  mount AvatarUploader::UploadEndpoint, at: '/uploads/avatars'
  mount FileUploader::UploadEndpoint, at: '/uploads/attachments'
  mount AvatarUploader::DownloadEndpoint, at: '/avatars'
  mount FileUploader::DownloadEndpoint, at: '/attachments'

  # ACCOUNT
  resource :account, only: [:show, :edit], path: 'account' do
    patch 'update_account', to: 'accounts#update_account'
    resources :charges, only: [:index, :show]
    resource :credit_card, only: [:update]
  end

  # COUPONS
  resources :coupons, only: [:show], path: 'coupon'

  # COURSES
  resources :courses do
    put :sort, on: :member, as: :sortable
    resource :enrollment, only: [:create], path: 'enroll'
    resources :lessons, only: [:show] do
      post :complete, on: :member
      get :preview, on: :member
    end
    get 'progress', on: :member
    get 'purchase', to: 'purchases#new'
    resource :purchase, only: [:create]
  end

  # DASHBOARD
  namespace :instructor do
    resource :dashboard, only: [:show]
  end

  # DISCOURSE
  resource :forum_sessions, only: :new
  get '/forum', to: redirect("#{Forum.url('session/sso')}")

  # DOWNLOADS
  concern :downloadable do
    get 'download', on: :member
  end

  # PAGES
  get '/contact' => 'pages#contact'
  post '/contact' => 'pages#submit_contact_form'
  get '/faq' => 'pages#faq'
  get '/privacy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  # SUBSCRIPTION
  resource :reactivation, only: [:create]
  resource :subscription, only: [:new, :create], path: 'subscribe'
  delete 'unsubscribe', to: 'subscriptions#destroy', as: 'cancel_subscription'

  # UPLOADS
  resources :uploads, only: [:download], concerns: :downloadable

  # WORKSHOPS
  resources :workshops do
    get 'purchase', to: 'purchases#new'
    resource :purchase, only: [:create]
  end
end

app/models/workshop.rb
class Workshop < ApplicationRecord
  include Concerns::Publishable
  include Concerns::Purchasable
  include Concerns::Sluggable
  include Concerns::Uploadable
  include Concerns::Videoable

  CACHE_KEY_BASE = ['models', model_name.name.humanize.downcase].freeze

  belongs_to :instructor, inverse_of: :workshops, class_name: 'User'

  validates :name, presence: true
  validates :short_description, presence: true
  validates :notes, presence: true
  validates :video, presence: true
  validates :instructor_id, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 9999.99 }

  accepts_nested_attributes_for :uploads, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :video, reject_if: :all_blank, allow_destroy: true

  def content_length
    video.video_duration
  end

  def has_attachments?
    uploads.any?
  end

  def is_free?
    price == 0
  end

  def watchable_for(user)
    user.has_access_to?(self) || is_free?
  end

  private

  def slug_source
    name
  end

  def self.content_length
    Rails.cache.fetch([CACHE_KEY_BASE, __method__, Workshop.video_cache_key]) do
      joins(:video).group('workshops.id').sum(:video_duration)
    end
  end

  def self.ordered
    order(created_at: :desc)
  end

  def self.video_cache_key
    Video.where(videoable_type: model_name.name.humanize).all.cache_key
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_workshop, only: [:show, :edit, :update, :destroy]

  def index
    authorize workshops
  end

  def show
  end

  def new
    @workshop = current_user.workshops.build
    authorize @workshop
  end

  def create
    @workshop = current_user.workshops.build(workshop_params)
    authorize @workshop
    if @workshop.save
      redirect_to @workshop
      flash[:success] = t('flash.workshops.create.success')
    else
      flash[:alert] = t('flash.workshops.create.alert')
      render :new
    end
  end

  def edit
  end

  def update
    if workshop.update(workshop_params)
      redirect_to workshop
      flash[:success] = t('flash.workshops.update.success')
    else
      flash[:alert] = t('flash.workshops.update.alert')
      render :edit
    end
  end

  def destroy
    workshop.destroy
    flash[:info] = t('flash.workshops.destroy.info')
    redirect_to root_path
  end

  private

  def workshop
    @workshop ||=
      Workshop.includes(:instructor, :uploads, :video).find_by_slug(params[:id])
  end
  helper_method :workshop

  def workshops
    @workshops ||= Workshop.published.ordered.includes(:instructor, :video).all
  end
  helper_method :workshops

  def authorize_workshop
    authorize workshop
  end

  def workshop_params
    params.require(:workshop).permit(:name, :status, :published_at, :short_description, :notes, :price,
      video_attributes: [:id, :video_url],
      uploads_attributes: [:id, :file, :_destroy]
    )
  end
end

app/views/workshops/_button_delete.html.haml
= link_to t('button.delete'), workshop_path(resource), method: :delete, data: { confirm: 'Are you sure you want to delete this workshop?' }, class: 'button button-red'

app/views/workshops/_button_edit.html.haml
= link_to t('button.edit'), edit_workshop_path(resource), class: 'button button-green'

app/views/workshops/_button_purchase.html.haml
- if resource.is_free?
  = link_to t('button.account.sign_up'), new_user_registration_path, class: 'button button-green' unless user_signed_in?
- else
  = link_to t('button.purchase.with_price', price: resource.price), workshop_purchase_path(workshop_id: resource), class: 'button button-green'

app/views/workshops/_comments.html.haml
- unless Rails.env.test?
  #discourse-comments
  :javascript
    DiscourseEmbed = { discourseUrl: "#{Forum.url}",
                       discourseEmbedUrl: "#{workshop_url(workshop)}" };

    (function() {
      var d = document.createElement('script'); d.type = 'text/javascript'; d.async = true;
      d.src = DiscourseEmbed.discourseUrl + 'javascripts/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(d);
    })();

app/views/workshops/_form.html.haml
= simple_form_for @workshop do |f|
  .row
    = f.input :name, autofocus: true, wrapper_html: { class: 'twelve columns reset-mobile-column' }
  .row
    = f.input :status, collection: Workshop::STATUSES, wrapper_html: { class: 'five columns reset-mobile-column', data: { trigger: 'datetimepicker' } }, include_blank: false, selected: label_for(@workshop)
    = f.input :published_at, as: :datetime, wrapper_html: { class: 'seven columns reset-mobile-column datetimepicker', data: { toggle: 'datetimepicker' } }
  .row
    = f.input :price, input_html: { value: f.object.price || 0.0 }, wrapper_html: { class: 'twelve columns reset-mobile-column' }
  .row
    = f.simple_fields_for :video, (f.object.build_video unless f.object.video) do |video|
      = video.input :video_url, wrapper_html: { class: 'twelve columns reset-mobile-column' }
  .row
    = f.input :short_description, as: :text, input_html: { style: 'min-height: 65px;' }, hint: t('simple_form.hints.workshops.short_description'), wrapper_html: { class: 'twelve columns reset-mobile-column' }
  .row
    = f.input :notes, wrapper_html: { class: 'twelve columns reset-mobile-column' }
  .row
    = f.simple_fields_for :uploads, f.object.uploads.build do |upload|
      = upload.input :file, as: :hidden, input_html: { value: upload.object.cached_file_data }
      = upload.input :file, as: :file, wrapper_html: { class: 'twelve columns reset-mobile-column' }
  .row
    .twelve.columns.reset-mobile-column
      = f.button :button, class: 'button-large button-purple pull-right margin-top-25', data: { disable_with: "#{image_tag 'signal.svg', class: 'loader'} #{t('button.disabled.saving')}" }

app/views/workshops/_workshop.html.haml
- cache [cache_key_base, workshop] do
  .tile.stacked
    .tile-header
      = link_to workshop_path(workshop) do
        = icon_tag 'play-circle'
        %h1= workshop.name
        %small= duration_in_hours(content_length_for(workshop)) if workshop.video.present?
    .tile-content
      .tile-meta
        %small Presented by
        %h3= workshop.instructor.name
      %figure
        = user_avatar(workshop.instructor, src: workshop.instructor.avatar_url(:medium), class: 'avatar-default', alt: workshop.instructor.name, width: '45px', height: '45px')
    %p.description= workshop.short_description

app/views/workshops/edit.html.haml
- content_for :page_title, workshop.name
- content_for :page_description, workshop.short_description

= render 'form'

app/views/workshops/index.html.haml
- content_for :page_title, title

- cache [cache_key_base, index_cache_key(:workshop)] do
  .tile-container.flex-grid
    = render partial: 'workshop', collection: @workshops, cached: true

app/views/workshops/new.html.haml
- content_for :page_title, title

= render 'form'

app/views/workshops/show.html.haml
- content_for :page_title, workshop.name
- content_for :page_description, workshop.short_description

.library-header
  %h1
    = workshop.name
  .library-meta
    = user_avatar(workshop.instructor, src: workshop.instructor.avatar_url(:medium), class: 'avatar-circle', alt: workshop.instructor.name, width: '45px', height: '45px')
    %h5= workshop.instructor.name
.box
  - if user_signed_in?
    .box-header.video-container
      = embed_video(workshop.video) if policy_scope(workshop)
  .box-content
    %p= workshop.short_description
    %ul.tabs
      %li.tab-button.pull-right
        -if user_signed_in?
          = render 'button_edit', resource: workshop if policy(workshop).update?
          = render 'button_delete', resource: workshop if policy(workshop).destroy?
          = render 'button_purchase', resource: workshop unless current_user.has_access_to?(workshop) || policy(workshop).destroy? || policy(workshop).update?
        - else
          = render 'button_purchase', resource: workshop
      %li.tab-header
        %a.tab-link{ href: 'javascript:void(0)', data: { toggle: 'tab' } }
          = t('workshops.notes')
        .tab-content
          = format_markdown workshop.notes
      - if user_signed_in? && (workshop.has_attachments? && policy_scope(workshop))
        %li.tab-header
          %a.tab-link{ href: 'javascript:void(0)', data: { toggle: 'tab' } } #{ t('workshops.attachments') }
          .tab-content
            %ul.attachment-list
              - workshop.uploads.each do |upload|
                = render 'attachment', upload: upload
      %li.tab-header
        %a.tab-link{ href: 'javascript:void(0)', data: { toggle: 'tab' } }
          = t('workshops.questions')
        .tab-content
          = render 'comments', workshop: workshop