config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }, path: 'account', path_names: { sign_in: 'signin', sign_out: 'signout', password: 'password', sign_up: 'signup', edit: 'password/change' }

  authenticated :user do
    root 'student/dashboards#show', as: :authenticated_root
  end

  root 'pages#home'

  # STRIPE
  mount StripeEvent::Engine, at: '/stripe/webhook'

  # SHRINE
  mount AvatarUploader::UploadEndpoint, at: '/uploads/avatars'
  mount FileUploader::UploadEndpoint, at: '/uploads/attachments'
  mount AvatarUploader::DownloadEndpoint, at: '/avatars'
  mount FileUploader::DownloadEndpoint, at: '/attachments'

  # ACCOUNT
  resource :account, only: [:show, :edit], path: 'account' do
    patch 'update_account', to: 'accounts#update_account'
    resources :charges, only: [:index, :show]
    resource :credit_card, only: [:update]
  end

  # COUPONS
  resources :coupons, only: [:show], path: 'coupon'

  # COURSES
  resources :courses do
    put :sort, on: :member, as: :sortable
    resource :enrollment, only: [:create], path: 'enroll'
    resources :lessons, only: [:show] do
      post :complete, on: :member
      get :preview, on: :member
    end
    get 'progress', on: :member
    get 'purchase', to: 'purchases#new'
    resource :purchase, only: [:create]
  end

  # DASHBOARD
  namespace :instructor do
    resource :dashboard, only: [:show]
  end

  # DISCOURSE
  resource :forum_sessions, only: :new
  get '/forum', to: redirect("#{Forum.url('session/sso')}")

  # DOWNLOADS
  concern :downloadable do
    get 'download', on: :member
  end

  # PAGES
  get '/contact' => 'pages#contact'
  post '/contact' => 'pages#submit_contact_form'
  get '/faq' => 'pages#faq'
  get '/privacy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  # SUBSCRIPTION
  resource :reactivation, only: [:create]
  resource :subscription, only: [:new, :create], path: 'subscribe'
  delete 'unsubscribe', to: 'subscriptions#destroy', as: 'cancel_subscription'

  # UPLOADS
  resources :uploads, only: [:download], concerns: :downloadable

  # WORKSHOPS
  resources :workshops do
    get 'purchase', to: 'purchases#new'
    resource :purchase, only: [:create]
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :plan, inverse_of: :subscriptions
  belongs_to :subscriber, inverse_of: :subscription, class_name: 'User'

  validates_presence_of :plan_id, :subscriber_id

  scope :active, -> { with_status :active }

  state_machine :status, initial: :initial do
    state :initial
    state :active
    state :canceled

    after_transition canceled: :active do |subscription|
      subscription.update_column(:canceled_on, nil)
    end

    after_transition any => :canceled do |subscription|
      subscription.update(
        canceled_on: Time.zone.today,
        scheduled_for_cancellation_on: nil
      )
    end

    event :activate do
      transition [:initial, :canceled] => :active
    end

    event :cancel do
      transition active: :canceled
    end
  end

  delegate :stripe_customer_id, to: :subscriber
  delegate :interval_count, :interval_unit, :price, :stripe_plan_id, to: :plan

  attr_accessor :stripe_coupon_id, :stripe_token

  def fulfill
    transaction do
      create_subscription
      activate
    end
  end

  def coupon
    @coupon ||= Coupon.new(stripe_coupon_id)
  end

  def has_invalid_coupon?
    stripe_coupon_id.present? && !coupon.valid?
  end

  def scheduled_for_cancellation?
    scheduled_for_cancellation_on.present?
  end

  def reactivate
    update_column(:scheduled_for_cancellation_on, nil)
    stripe_subscription.reactivate
  end

  private

  def create_subscription
    if create_stripe_subscription && save
      self.stripe_subscription_id = stripe_subscription.id
    end
  end

  def create_stripe_subscription
    stripe_subscription.create
  end

  def stripe_subscription
    @stripe_subscription ||= StripeSubscription.new(self)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  before_action :redirect_to_signup, only: [:new]
  before_action :redirect_when_plan_not_found, only: [:new, :create]

  def new
    authorize :subscription
    build_subscription({}) do |subscription|
      @subscription = subscription
      render :new
    end
  end

  def create
    authorize :subscription
    build_subscription(subscription_params) do |subscription|
      success = subscription.fulfill
      if success
        session.delete(:coupon)
        track_subscription
        redirect_after_subscription
      else
        @subscription = subscription
        flash[:alert] = t('flash.subscriptions.create.error')
        render :new
      end
    end
  end

  def destroy
    authorize :subscription
    @cancellation = Cancellation.new(
      subscription: current_user.subscription
    ).schedule

    flash[:info] = t('flash.subscriptions.cancel')
    redirect_to root_path
  end

  private

  def build_subscription(arguments)
    subscription = Subscription.where(subscriber: current_user).first_or_initialize
    subscription.attributes = arguments
        .merge(default_params)
        .merge(coupon_params)

    if subscription.has_invalid_coupon?
      redirect_from_invalid_coupon
    else
      yield subscription
    end
  end

  def default_params
    {
      plan: plan
    }
  end

  def coupon_params
    {
      stripe_coupon_id: session[:coupon]
    }
  end

  def subscription_params
    params.require(:subscription).permit(
      :stripe_token
    )
  end

  def plan
    @plan ||= Plan.find_by(id: params[:plan])
  end

  def redirect_to_signup
    unless user_signed_in?
      session['user_return_to'] = new_subscription_path(plan: params[:plan])
      redirect_to new_user_registration_path
    end
  end

  def redirect_when_plan_not_found
    unless plan.present?
      flash[:info] = t('flash.plans.not_found')
      redirect_to root_path
    end
  end

  def redirect_from_invalid_coupon
    flash[:warning] = t('flash.subscriptions.invalid_coupon', code: session[:coupon])
    session.delete(:coupon)
    redirect_to new_subscription_path(plan: params[:plan])
  end

  def redirect_after_subscription
    flash[:success] = t('flash.subscriptions.create.success', plan: plan.name)
    redirect_to root_path
  end

  def track_subscription
    analytics.track_subscribed(
      plan: plan.name,
      revenue: '99.0'.freeze
    )
  end
end

app/views/subscriptions/_cancel.html.haml
= link_to t('button.subscription.cancel'),
  cancel_subscription_path,
  class: 'button button-red button-small pull-right',
  method: :delete,
  data: { confirm: t('subscriptions.cancel.confirm'), disable_with: "#{image_tag 'signal.svg', class: 'loader'} #{t('button.disabled.canceling')}" }

app/views/subscriptions/_form.html.haml
.checkout-form
  %h4 Payment Information
  = simple_form_for :subscription, url: subscription_path, html: { id: 'subscription-form' } do |f|
    .has-errors
    = render 'credit_card_fields'
    = f.input :plan, as: :hidden, input_html: { name: 'plan', value: "#{ params[:plan] }" }
    = f.button :button, t('button.subscription.new'), class: 'button-large button-purple wide', data: { disable_with: "#{image_tag 'signal.svg', class: 'loader'} #{t('button.disabled.processing')}"}
    %p.text-small.text-muted.content-center You can cancel or pause your subscription at any time.

app/views/subscriptions/_reactivate.html.haml
= form_for :reactivation, url: reactivation_path, html: { class: 'reactivate' } do |f|
  = f.button t('button.subscription.reactivate'),
    class: 'button button-green button-small relative pull-right',
    data: { disable_with: "#{image_tag 'signal.svg', class: 'loader'} #{t('button.disabled.reactivating')}", tooltip: t('tooltip.reactivate'), tooltip_position: 'left middle' }

app/views/subscriptions/_sidebar.html.haml
.checkout-sidebar
  %h4 Order Summary
  .order-summary
    .table-row.table-header
      .title= @plan.name
      .order-price
        %span.currency £
        %span.price= @subscription.price
        %span.term / #{ @subscription.interval_unit }
    .table-row
      %div Unlimited Access to All Courses
      = icon_tag 'check'
    .table-row
      %div Self-Paced
      = icon_tag 'check'
    .table-row
      %div Direct Access to Our Instructors
      = icon_tag 'check'
    .table-row
      %div Get help in our members-only forum
      = icon_tag 'check'
    .table-row
      %div Cancel Online Any Time
      = icon_tag 'check'
    .divider
    .table-row
      %div Billing Cycle
      %div Every #{ subscription_interval(@subscription) }
    - if @subscription.stripe_coupon_id
      .table-row
        %div Coupon Applied
        .sbold= @subscription.stripe_coupon_id
    .divider
    .table-row.table-header
      .title Total Due Today
      = checkout_price(@subscription)
    - if @subscription.stripe_coupon_id
      .table-row.table-note
        .text-muted.content-center= subscription_with_coupon(@subscription)
  .order-summary-footer
    %p.text-small.text-muted.uppercase.content-center
      = icon_tag 'lock', class: 'icon-green'
      Secure Server

app/views/subscriptions/_subscription.html.haml
.box
  .box-header
    %h3.inline-block Subscription
  .box-content
    - if subscription.active?
      %p.subscription
        %b #{subscription.plan.name}
        active since #{subscription.created_at.to_s(:simple)}
      - unless subscription.scheduled_for_cancellation?
        = render 'subscriptions/cancel'
      - if subscription.scheduled_for_cancellation?
        %p.subscription
          = t('subscriptions.cancellation_scheduled_on', date: subscription.scheduled_for_cancellation_on.to_s(:simple))
        = render 'subscriptions/reactivate'
    - else
      %p.subscription
        = t('subscriptions.canceled_on', date: subscription.canceled_on.to_s(:simple))

app/views/subscriptions/_title.html.haml
%h1 Start your subscription today. You're gonna love it.

app/views/subscriptions/new.html.haml
- body_css 'checkout'
- content_for :page_title, title

= render 'title'
= render 'form'
= render 'sidebar'