config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }, path: 'account', path_names: { sign_in: 'signin', sign_out: 'signout', password: 'password', sign_up: 'signup', edit: 'password/change' }

  authenticated :user do
    root 'student/dashboards#show', as: :authenticated_root
  end

  root 'pages#home'

  # STRIPE
  mount StripeEvent::Engine, at: '/stripe/webhook'

  # SHRINE
  mount AvatarUploader::UploadEndpoint, at: '/uploads/avatars'
  mount FileUploader::UploadEndpoint, at: '/uploads/attachments'
  mount AvatarUploader::DownloadEndpoint, at: '/avatars'
  mount FileUploader::DownloadEndpoint, at: '/attachments'

  # ACCOUNT
  resource :account, only: [:show, :edit], path: 'account' do
    patch 'update_account', to: 'accounts#update_account'
    resources :charges, only: [:index, :show]
    resource :credit_card, only: [:update]
  end

  # COUPONS
  resources :coupons, only: [:show], path: 'coupon'

  # COURSES
  resources :courses do
    put :sort, on: :member, as: :sortable
    resource :enrollment, only: [:create], path: 'enroll'
    resources :lessons, only: [:show] do
      post :complete, on: :member
      get :preview, on: :member
    end
    get 'progress', on: :member
    get 'purchase', to: 'purchases#new'
    resource :purchase, only: [:create]
  end

  # DASHBOARD
  namespace :instructor do
    resource :dashboard, only: [:show]
  end

  # DISCOURSE
  resource :forum_sessions, only: :new
  get '/forum', to: redirect("#{Forum.url('session/sso')}")

  # DOWNLOADS
  concern :downloadable do
    get 'download', on: :member
  end

  # PAGES
  get '/contact' => 'pages#contact'
  post '/contact' => 'pages#submit_contact_form'
  get '/faq' => 'pages#faq'
  get '/privacy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  # SUBSCRIPTION
  resource :reactivation, only: [:create]
  resource :subscription, only: [:new, :create], path: 'subscribe'
  delete 'unsubscribe', to: 'subscriptions#destroy', as: 'cancel_subscription'

  # UPLOADS
  resources :uploads, only: [:download], concerns: :downloadable

  # WORKSHOPS
  resources :workshops do
    get 'purchase', to: 'purchases#new'
    resource :purchase, only: [:create]
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_course, only: [:show, :edit, :update, :destroy, :progress]

  def index
    @courses = Course.visible.ordered.includes(:instructor)
    authorize @courses
    gon.push(scheduledCourses: @courses.scheduled.ids.to_s)
  end

  def show
    @sections = @course.modules
  end

  def new
    @course = current_user.courses_as_instructor.build
    authorize @course
  end

  def create
    @course = current_user.courses_as_instructor.build(course_params)
    authorize @course
    if @course.save
      redirect_to @course
      flash[:success] = t('flash.courses.create.success')
    else
      flash[:alert] = t('flash.courses.create.alert')
      render :new
    end
  end

  def edit; end

  def update
    if @course.update(course_params)
      redirect_to @course
      flash[:success] = t('flash.courses.update.success')
    else
      flash[:alert] = t('flash.courses.update.alert')
      render :edit
    end
  end

  def destroy
    @course.destroy
    flash[:info] = t('flash.courses.destroy.info')
    redirect_to root_path
  end

  def progress
    @sections = @course.modules
  end

  def sort
    authorize :course
    if params[:sort_sections]
      params[:sort_sections].each do |key, value|
        Section.find(value[:section_id]).update_attribute(:position, value[:position])
      end
      params[:sort_lessons].each do |key, value|
        Lesson.find(value[:lesson_id]).update_attribute(:position, value[:position])
      end
    elsif params[:lesson_order]
      params[:lesson_order].each do |key, value|
        Lesson.find(value[:id]).update(section_id: value[:section_id], position: value[:position])
      end
    end
    head :ok
  end

  private

  def set_course
    @course ||= Course.includes(:instructor, :video).find_by_slug(params[:id])
    authorize @course
  end

  def course_params
    params.require(:course).permit(:name, :status, :published_at, :short_description, :description, :price,
      video_attributes: [ :id, :video_url ],
      sections_attributes: [ :id, :title, :objective, :_destroy,
        lessons_attributes: [ :id, :title, :notes, :_destroy,
          video_attributes: [ :id, :video_url ],
          uploads_attributes: [ :id, :file, :_destroy ]
        ]
      ]
    )
  end
end

app/views/courses/_button_continue.html.haml
- if resource.progress(current_user) != 100
  = link_to t('button.course.continue'), course_lesson_path(resource, resource.first_remaining_lesson_for(current_user)), class: css_class
- else
  = link_to t('button.course.completed'), progress_course_path(resource), class: css_class

app/views/courses/_button_delete.html.haml
- if current_user.is_admin?
  = link_to t('button.delete'),
            course_path(resource),
            method: :delete,
            data: { confirm: 'Are you sure you want to delete this course?' },
            class: 'button button-red'

app/views/courses/_button_edit.html.haml
= link_to t('button.edit'), edit_course_path(resource), class: 'button button-green'

app/views/courses/_button_enroll.html.haml
- enrollment = current_user.enrollments.build( course_id: resource.id )
= form_for enrollment, url: course_enrollment_path(resource) do |f|
  = f.button t('button.course.enroll'), class: 'button button-purple', data: { disable_with: "#{image_tag 'signal.svg', class: 'loader'} #{t('button.disabled.enrolling')}" }

app/views/courses/_button_purchase.html.haml
= link_to t('button.purchase.with_price', price: resource.price), course_purchase_path(course_id: resource), class: 'button button-green'

app/views/courses/_course.html.haml
- cache [cache_key_base, course] do
  .tile.stacked{ class: "tile-#{course.id}", data: { type: :course, id: course.id} }
    .tile-header
      = link_to course_path(course), data: { role: 'course_link' } do
        = icon_tag 'course'
        %h1= course.name
        %small
          = t('lessons.count', count: lesson_count_for(course))
          \/
          = duration_in_hours(content_length_for(course))
    .tile-content
      .tile-meta
        %small Instructed by
        %h3= course.instructor.name
      %figure
        = user_avatar(course.instructor, src: course.instructor.avatar_url(:medium), class: 'avatar-default', alt: course.instructor.name, width: '45px', height: '45px')
    %p.description= course.short_description

app/views/courses/_form.html.haml
= simple_form_for @course do |f|
  .row
    = f.input :name, wrapper_html: { class: 'twelve columns reset-mobile-column' }
  .row
    = f.input :status, collection: Course::STATUSES, wrapper_html: { class: 'five columns reset-mobile-column', data: { trigger: 'datetimepicker' } }, include_blank: false, selected: label_for(@course)
    = f.input :published_at, as: :datetime, wrapper_html: { class: 'seven columns reset-mobile-column datetimepicker', data: { toggle: 'datetimepicker' } }
  .row
    = f.input :short_description, as: :text, input_html: { style: 'min-height: 65px;' }, hint: t('simple_form.hints.courses.short_description'), wrapper_html: { class: 'twelve columns reset-mobile-column' }
  .row
    = f.input :description, wrapper_html: { class: 'twelve columns reset-mobile-column' }
  .row
    = f.input :price, wrapper_html: { class: 'twelve columns reset-mobile-column' }
  .row
    = f.simple_fields_for :video, (f.object.build_video unless f.object.video) do |video|
      = video.input :video_url, wrapper_html: { class: 'twelve columns reset-mobile-column' }
  #modules
    = f.simple_fields_for :sections do |ff|
      = render 'sections/form', f: ff
    #module_add.row
      = link_to_add_association 'Add module', f, :sections, partial: 'sections/form', class: 'twelve columns reset-mobile-column'
  .row
    .twelve.columns.reset-mobile-column
      = f.button :button, class: 'button-large button-purple pull-right margin-top-25', data: { disable_with: "#{image_tag 'signal.svg', class: 'loader'} #{t('button.disabled.saving')}" }

app/views/courses/edit.html.haml
- content_for :page_title, @course.name
- content_for :page_description, @course.short_description

= render 'form'

app/views/courses/index.html.haml
- content_for :page_title, title

- cache [cache_key_base, index_cache_key(:course)] do
  .tile-container.flex-grid
    = render partial: 'course', collection: @courses, cached: true

app/views/courses/progress.html.haml
- content_for :page_title, @course.name
- content_for :page_description, @course.short_description

.course-header
  %h1
    = @course.name
  %h3 Course progress
= render partial: 'sections/section_for_enrollees', collection: @sections, as: :section, locals: { css_class: '' }

app/views/courses/show.html.haml
- content_for :page_title, @course.name
- content_for :page_description, @course.short_description

.library-header
  %h1
    = @course.name
  .library-meta
    = user_avatar(@course.instructor, src: @course.instructor.avatar_url(:medium), class: 'avatar-circle', alt: @course.instructor.name, width: '45px', height: '45px')
    %h5= @course.instructor.name
.box
  .box-header.video-container
    = embed_video(@course.video)
  .box-content
    %p= @course.short_description
    %ul.tabs
      %li.tab-button.pull-right
        -if user_signed_in?
          - if !current_user.enrolled?(@course) && ( current_user.has_active_subscription? || current_user.purchased?(@course) )
            = render 'button_enroll', resource: @course
          - elsif current_user.is_admin? || current_user.id == @course.instructor_id
            = render 'button_edit', resource: @course
            = render 'button_delete', resource: @course
          - elsif current_user.enrolled?(@course)
            = render 'button_continue', resource: @course, css_class: 'button button-green'
          - elsif !( current_user.has_active_subscription? || current_user.purchased?(@course) )
            = render 'button_purchase', resource: @course
        - else
          -#= link_to t('button.subscription.new'), new_subscription_path(plan: 1), class: 'button button-green'
          = render 'button_purchase', resource: @course
      %li.tab-header
        %a.tab-link{ href: 'javascript:void(0)', data: { toggle: 'tab' } }
          = t('courses.description')
        .tab-content
          = format_markdown @course.description
      %li.tab-header
        %a.tab-link{ href: 'javascript:void(0)', data: { toggle: 'tab' } }
          = t('courses.curriculum')
        .tab-content
          - if !user_signed_in? || (!current_user.enrolled?(@course) && !(current_user.has_active_subscription? || current_user.purchased?(@course)))
            = render partial: 'sections/section_for_visitors', collection: @sections, as: :section, cached: true
          - else
            = render partial: 'sections/section_for_enrollees', collection: @sections, as: :section, locals: { css_class: 'compact' }
      - if policy(@course).update?
        %li.tab-header
          %a.tab-link{ href: 'javascript:void(0)', data: { toggle: 'tab' } }
            = t('courses.admin')
          .tab-content{ id: 'sortable', data: { url: "#{sortable_course_path(@course)}" } }
            = render partial: 'sections/section_for_admins', collection: @sections, as: :section, locals: { css_class: 'administrate' }, cached: true