config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }, path: 'account', path_names: { sign_in: 'signin', sign_out: 'signout', password: 'password', sign_up: 'signup', edit: 'password/change' }

  authenticated :user do
    root 'student/dashboards#show', as: :authenticated_root
  end

  root 'pages#home'

  # STRIPE
  mount StripeEvent::Engine, at: '/stripe/webhook'

  # SHRINE
  mount AvatarUploader::UploadEndpoint, at: '/uploads/avatars'
  mount FileUploader::UploadEndpoint, at: '/uploads/attachments'
  mount AvatarUploader::DownloadEndpoint, at: '/avatars'
  mount FileUploader::DownloadEndpoint, at: '/attachments'

  # ACCOUNT
  resource :account, only: [:show, :edit], path: 'account' do
    patch 'update_account', to: 'accounts#update_account'
    resources :charges, only: [:index, :show]
    resource :credit_card, only: [:update]
  end

  # COUPONS
  resources :coupons, only: [:show], path: 'coupon'

  # COURSES
  resources :courses do
    put :sort, on: :member, as: :sortable
    resource :enrollment, only: [:create], path: 'enroll'
    resources :lessons, only: [:show] do
      post :complete, on: :member
      get :preview, on: :member
    end
    get 'progress', on: :member
    get 'purchase', to: 'purchases#new'
    resource :purchase, only: [:create]
  end

  # DASHBOARD
  namespace :instructor do
    resource :dashboard, only: [:show]
  end

  # DISCOURSE
  resource :forum_sessions, only: :new
  get '/forum', to: redirect("#{Forum.url('session/sso')}")

  # DOWNLOADS
  concern :downloadable do
    get 'download', on: :member
  end

  # PAGES
  get '/contact' => 'pages#contact'
  post '/contact' => 'pages#submit_contact_form'
  get '/faq' => 'pages#faq'
  get '/privacy' => 'pages#privacy'
  get '/terms' => 'pages#terms'

  # SUBSCRIPTION
  resource :reactivation, only: [:create]
  resource :subscription, only: [:new, :create], path: 'subscribe'
  delete 'unsubscribe', to: 'subscriptions#destroy', as: 'cancel_subscription'

  # UPLOADS
  resources :uploads, only: [:download], concerns: :downloadable

  # WORKSHOPS
  resources :workshops do
    get 'purchase', to: 'purchases#new'
    resource :purchase, only: [:create]
  end
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :user, inverse_of: :charges

  validates_presence_of :user_id
  validates :stripe_charge_id, uniqueness: true

  after_commit :send_receipt

  def receipt_number
    "#{created_at.to_s(:receipt)}-#{id}"
  end

  def receipt
    Receipt.new(
      id: receipt_number,
      product: product,
      company: {
        name: Settings.company.name,
        address: Settings.company.address,
        email: Settings.company.email,
        logo: Rails.root.join('app/assets/images/logo-default.png')
      },
      receipt_items: receipt_items,
      font: {
        bold: Rails.root.join('app/assets/fonts/lato-black.ttf'),
        normal: Rails.root.join('app/assets/fonts/lato-regular.ttf')
      }
    )
  end

  def receipt_items
    items = [
      ['Date',            "<b>#{created_at.to_s(:default)}"],
      ['Account billed',  "<b>#{user.name}</b> (#{user.email})"],
      ['Item',            "<b>#{product}</b>"],
      ['Amount',          "<b>GBP £#{amount}"],
      ['Charged to',      "<b>#{card_brand}</b> xxxx-#{card_last4}"],
      ['Transaction ID',  "<b>#{stripe_charge_id}</b>"]
    ]
  end

  def send_receipt
    SendChargeReceiptEmailWorker.perform_async(user_id, id)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_charge, only: [:show]

  def index
    @charges = policy_scope(Charge).order('created_at DESC')
    authorize @charges
  end

  def show
    respond_to do |format|
      format.pdf {
        send_data @charge.receipt.render,
          filename: "receipt-#{@charge.receipt_number}.pdf",
          type: 'application/pdf',
          disposition: :attachment
      }
    end
  end

  private

  def set_charge
    @charge = Charge.find(params[:id])
    authorize @charge
  end
end

app/views/charges/_charge.html.haml
- cache [cache_key_base, current_user.id, charge] do
  %tr
    %td= charge.receipt_number
    %td= charge.created_at.to_s(:default)
    %td= charge.product
    %td= "xxxx-#{charge.card_last4}"
    %td= "£#{charge.amount.to_s}"
    %td
      = link_to account_charge_path(charge, format: :pdf) do
        = icon_tag :receipt, size: :xl

app/views/charges/_charges.html.haml
.box
  .box-header
    %h3 Billing History
  .box-content
    %table
      %thead
        %tr
          %th Receipt no.
          %th Date
          %th Product
          %th Card charged
          %th Amount
          %th
      %tbody
        = render partial: 'charge', collection: @charges, cached: true

app/views/charges/index.html.haml
- content_for :page_title, title(user_name: current_user.name)

.row
  = render partial: 'accounts/sidebar'
  .nine.columns.reset-mobile-column
    = render 'accounts/credit_card' if current_user.has_credit_card?
    = render 'charges'
    = render current_user.subscription if current_user.subscription